<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migrations\20230612105600_NotesMigration.cs" />
    <Compile Remove="Migrations\20230612105600_NotesMigration.Designer.cs" />
    <Compile Remove="Migrations\20230612110420_NoteMigration.cs" />
    <Compile Remove="Migrations\20230612110420_NoteMigration.Designer.cs" />
    <Compile Remove="Migrations\20230612115933_NotesInfoMigration.cs" />
    <Compile Remove="Migrations\20230612115933_NotesInfoMigration.Designer.cs" />
    <Compile Remove="Migrations\20230613042125_NotesMigration.cs" />
    <Compile Remove="Migrations\20230613042125_NotesMigration.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.30.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.30.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonLayer\CommonLayer.csproj" />
  </ItemGroup>

</Project>
